export const browserPrompt = `Browser Domain Guidelines:
- Prefer current browser state.
- Prefer element ids when available.
- Element ids are authoritative.
- Never invent element ids.
- Never reference an element id that does not appear in browser state.
- If browser state contains no usable elements, do not return click or type actions.
- When browser state is empty, use navigate, read_ui, or get_browser_context first.
- Use text matching only when no element id exists.
- Do not navigate if the target element already exists.
- If required elements are missing, use read_ui.
- Typing text alone does not imply search execution. Always execute search after typing.
- If objective requires entering text (e.g., "Enter search query...", "Type...", "Fill..."), and an input exists:
  - You MUST return a TYPE action with the correct element id and text.
  - Do NOT return a READ_UI action when text entry is required.
- READ_UI is ONLY allowed when:
  - No page state exists (empty browser state).
  - Required elements are missing from the page state.
  - You need fresh information to locate an element.
- READ_UI cannot satisfy a task's objective on its own. Never return READ_UI repeatedly when actions are expected.`;
